parser: babel

printWidth: 120
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
endOfLine: lf

requirePragma: false
insertPragma: false

overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    options:
      parser: typescript
  - files: '*.json'
    options:
      parser: json
  - files:
      - '*.yml'
      - '*.yaml'
    options:
      parser: yaml